class VotingQueRepo {
  bool? success;
  dynamic data;

  VotingQueRepo({this.success, this.data});

  factory VotingQueRepo.fromJson(Map<dynamic, dynamic> json) {
    try {
      return VotingQueRepo(
          success: json['success'],
          data: json['data'],
      );
    } catch (error) {
      return VotingQueRepo(
        success: false,
        data: null,
      );
    }
  }
  // Autogenerated.fromJson(Map<String, dynamic> json) {
  //   success = json['success'];
  //   if (json['data'] != null) {
  //     data = <Data>[];
  //     json['data'].forEach((v) {
  //       data!.add(new Data.fromJson(v));
  //     });
  //   }
  // }
  //
  // Map<String, dynamic> toJson() {
  //   final Map<String, dynamic> data = new Map<String, dynamic>();
  //   data['success'] = this.success;
  //   if (this.data != null) {
  //     data['data'] = this.data!.map((v) => v.toJson()).toList();
  //   }
  //   return data;
  // }
}

class VotingQueModel {
  int? id;
  String? question;
  String? createdAt;
  String? updatedAt;

  VotingQueModel({this.id, this.question, this.createdAt, this.updatedAt});

  VotingQueModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    question = json['question'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['question'] = this.question;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    return data;
  }
}